project:
  type: website

website:
  title: "brainworkup.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - content/posts/
format:
  html:
    theme: cosmo
    css: styles.css
