project:
  type: website

website:
  title: "brainworkup.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
<<<<<<< HEAD

=======
>>>>>>> 5ebd5c7 (Quarto repo now)
format:
  html:
    theme: cosmo
    css: styles.css
<<<<<<< HEAD
=======



>>>>>>> 5ebd5c7 (Quarto repo now)
